apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  che-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: che
      type: prometheus
      access: proxy
      url: http://prometheus:9090
